"""Add image_url and billing fields

Revision ID: 6da61be109b6
Revises: 9d50bd2df191
Create Date: 2026-05-06 22:04:21.319708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da61be109b6'
down_revision = '9d50bd2df191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('billing_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_orders_billing_address_id_addresses', 'addresses', ['billing_address_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_billing_address_id_addresses', type_='foreignkey')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('billing_phone')
        batch_op.drop_column('billing_email')
        batch_op.drop_column('billing_name')
        batch_op.drop_column('billing_address_id')

    # ### end Alembic commands ###
